server:
  port: 8308

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/db_terminal?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&nullNamePatternMatchesAll=true&serverTimezone=Asia/Shanghai&useSSL=false
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: 123456
    filters:  stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    initialSize:  2
    minIdle: 1
    maxActive: 4
    maxWait: 60000
