spring:
  profiles:
    active: dev

  http:
    encoding:
      enable: ture
      charset: utf-8

  mvc:
    view:
      prefix: /WEB-INF/page/
      suffix: .jsp

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.demo.gradle.entity.po

# SQL日志配置
logging:
  level:
    com.demo.gradle.entity.dao: DEBUG

virus:
  info:
    province: Hubei
    count: 5471